config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get '/users', to: 'users#users', as: 'users'
  resources :tweets
  resources :relationships
  resources :users do
    member do
      get :following, :followers
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

# get '/url', to: 'controller#method' as: 'some term'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  #attr_accessor :username

  # helper methods

  # follow another user
  def follow(other)
    active_relationships.create(followed_id: other.id)
  end

  # unfollow another user
  def unfollow(other)
    active_relationships.find_by(followed_id: other.id).destroy
  end

  # is following a user?
  def following?(other)
    following.include?(other)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation, :remember_me])
   devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :username, :email, :password, :remember_me])
   devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to tweets_path
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    redirect_back fallback_location: root_path
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    redirect_back fallback_location: root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :find_tweet, only: [:destroy, :show]

  def create
    @tweet = Tweet.new(tweet_params.merge(user_id: current_user.id))
    @tweet.save

    redirect_to new_tweet_path
  end

  def new
    redirect_to tweets_path
  end

  def destroy
    @tweet.destroy

    redirect_to tweets_path
  end

  def index
    @tweet = Tweet.new
    @tweets = Tweet.order(created_at: :desc)
  end

  def show
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content)
  end

  def find_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def users
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    @user_tweets = @user.tweets.order(created_at: :desc)
  end

  def destroy
   @user = User.find(params[:id])

   if @user.destroy
       redirect_to root_url, notice: "User deleted."
   end
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def display_name(user)
    user == current_user ? 'Me' : user.email
  end
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <h1> This is the home page for signed in. </h1>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
<% else %>
<div class="container-fluid">
  <div class="jumbotron vertical-center">
    <div class="log_in">
      <h2>Log in</h2>
      <%= form_for(User.new, as: "user", url: session_path("user")) do |f| %>
        <div class="field">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true %>
        </div>

        <div class="field">
        <%= f.label :username %><br />
        <%= f.text_field :username, autofocus: true %>
        </div>

        <div class="field">
          <%= f.label :password %><br />
          <%= f.password_field :password, autocomplete: "off" %>
        </div>

          <div class="field">
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
          </div>
        <div class="action_login">
          <%= f.submit "Log in" %>
        </div>
      <% end %>
    </div>
    <div class="sign_up">
      <h2>Sign up</h2>
        <%= form_for(User.new, as: "user", url: registration_path("user")) do |f| %>

        <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true %>
        </div>

        <div class="field">
        <%= f.label :username %><br />
        <%= f.text_field :username, autofocus: true %>
        </div>

        <div class="field">
          <%= f.label :password %>
          <%  if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "off" %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off" %>
        </div>

        <div class="action_signup">
          <%= f.submit "Sign up" %>
        </div>
        <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Header", root_path, id: "logo" %>
    <%= link_to "Home", tweets_path, id: "homenav" %>
    <%= link_to tweets_path do %>
      <%= image_tag "baek.jpg", id: "baekhyun" %>
    <% end %>
    <%= render '/components/log_out_button' if user_signed_in?%>
    <nav>
      <ul class="nav navbar-nav navbar-right">
</ul>
</nav>
</div>
</header>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to ('Home'), tweets_path %> </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Me <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to ('Profile'), user_path(current_user.id) if user_signed_in? %></li>
            <li role="separator" class="divider"></li>
            <li> <%= render '/components/log_out_button' if user_signed_in?%> </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Twittah</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render "layouts/nav" %>
    <div class="container">
      <%=yield %>
    </div>
    <%= render "layouts/footer" %>

  </body>
</html>

app/views/tweets/index.html.erb
<!-- row 1 -->
<!-- column 1 -->
<div class="row">
  <div class="col-xs-3">
    <div class="panel panel-default">
      <div class="panel body">
        <h1> Welcome, <%= current_user.username %>! </h1>
        <h2> Following: <%= current_user.following.count %> </h2>
        <h2> Followers: <%= current_user.followers.count %> </h2>
        <h3> Posts: <%= current_user.tweets.count %></h3>
      </div>
    </div>
  </div>

<!-- column 2 -->
  <div class="col-xs-6">
    <div class="panel panel-default">
      <div class="panel body">
        <%= form_for @tweet, :url => url_for(:controller => 'tweets', :action => 'create') do |f| %>
          <div class="form-group">
            <%= f.text_area :content, class: 'form-control', placeholder: "What's happening?" %>
          </div>
          <div class="form-group">
            <%= f.submit "Tweet", class: 'btn btn-secondary', id: "tweetbutton" %>
          </div>
        <% end %>

        <% @tweets.each do |tweet| %>
          <section className='tweet-box'>
            <h3 class="td_email"> <%= link_to tweet.user.email, user_path(tweet.user) %> </h3>
            <span> <%= tweet.content %> </span>
            <time> <%= time_ago_in_words(tweet.created_at) %> </time>
              <div>
                <%= link_to "Delete", tweet, method: :delete %>
              </div>
          </section>
        <% end %>
      </div>
    </div>
  </div>

<!-- column 3 -->
  <div class="col-xs-3">
    <div class="panel panel-default">
      <div class="panel body">
          <p> This is the 3rd column </p>
      </div>
    </div>
  </div>
</div>

<!-- row 2 -->
<div class="row">
  <div class="col-xs-3">
    <div class="panel panel-default">
      <div class="panel body">
        <p> Trends </p>
      </div>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<p>
  <strong> Content </strong>
  <%= @tweet.content %>
</p>

<p>
  <strong> User: </strong>
  <%= @tweet.user.email %>
</p>

<p>
  <strong> Created at: </strong>
  <%= @tweet.user.created_at %>
</p>

app/views/users/show.html.erb
<!-- row 1-->
<div class="row">
  <div class="col-xs-12">
    <div class="jumbotron">
      PROFILE BANNER
    </div>
  </div>
</div>

<!-- row 2 -->
<div class="row">
    <!--row 2, column1-->
    <div class="col-xs-3">
      <div class="panel panel-default">
        <div class="panel body">
          <h1> <%= display_name(@user) %> </h1>
      </div>
    </div>
  </div>

  <!-- row 2,column 2 -->
  <div class="col-xs-6">
    <div class="panel panel-default">
      <div class="panel body">
        <p> Following: <%= @user.following.count %> </p>
        <p> Followers: <%= @user.followers.count %> </p>
        <p> Posts: <%= @user.tweets.count %> </p>
        <%= render '/components/follow_button' unless current_user == @user %>
      </div>
    </div>
  </div>
</div>

<!-- row 2, column 3 -->
<div class="col-xs-offset-9">
  <div class="panel panel-default">
    <div class="panel body">
      <p> Trends </p>
    </div>
  </div>
</div>
</div>

<!--row 3 -->
<div class-"row">
  <!--row 3, column 1 -->
  <div class="col-xs-3">
    <div class="panel panel-default">
      <div class="panel body">
        about
      </div>
    </div>
  </div>

  <!--row 3, column 2 -->
  <div class="col-xs-6">
    <div class="panel panel-default">
      <div class="panel body">
        <p>
          <% @user_tweets.each do |tweet| %>
            <section className='tweet-box'>
              <span> <%= tweet.content %> </span>
              <time> <%= time_ago_in_words(tweet.created_at) %> </time>
                <div>
                  <%= link_to "Delete", tweet, method: :delete %>
                </div>
            </section>
          <% end %>
        </p>
      </div>
    </div>
  </div>

app/views/users/users.html.erb
<h1> This is a list of users: </h1>

<% @user.each do |user| %>
  <p> <%= user.email %> </p>
<% end %>